"""Comprehensive examples testing — mock suite + optional real-mode on this host."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

from tests.conftest import cli_argv
from tests.examples.capabilities import probe_machine
from tests.examples.catalog import ALL_EXAMPLES
from tests.examples.command_catalog import DEFAULT_COMMANDS, REAL_COMMANDS, CommandSpec
from tests.examples.conftest import playwright_python, run_shell


def _missing(caps, requires: tuple[str, ...]) -> list[str]:
    return [r for r in requires if not caps.available(r)]


def _resolve_argv(spec: CommandSpec, repo_root: Path, env: dict) -> list[str]:
    argv = list(spec.argv)
    if "__PROMPT__" in argv:
        prompt = (
            repo_root / "examples/07_invoices_agent/create_invoices_agent_prompt.txt"
        ).read_text(encoding="utf-8").strip()
        argv = [prompt if a == "__PROMPT__" else a for a in argv]
    if argv and argv[0] in {"python", "python3"}:
        return [env.get("PYTHON", sys.executable), *argv[1:]]
    if argv and argv[0] in {"uri3", "uri", "hypervisor", "touri", "uri2ops", "uri2flow", "nl2uri"}:
        return cli_argv(argv[0], *argv[1:], env=env, repo_root=repo_root)
    return argv


def _run_spec(spec: CommandSpec, repo_root: Path, examples_env: dict) -> None:
    python = playwright_python(repo_root) or sys.executable
    examples_env = {**examples_env, "PYTHON": python}
    argv = _resolve_argv(spec, repo_root, examples_env)
    if spec.id == "ex03-ssh":
        pytest.importorskip("docker")
        from tests.examples.conftest import docker_available

        if not docker_available():
            pytest.skip("docker not available")
        up = run_shell(repo_root, ["make", "docker-testenv-up"], env=examples_env, timeout_s=240)
        assert up.returncode == 0, up.stderr
        env = {
            **examples_env,
            "HYPERVISOR_SSH_PASSWORD": examples_env.get("HYPERVISOR_SSH_PASSWORD", "deploy"),
        }
        try:
            result = run_shell(repo_root, argv, env=env, timeout_s=spec.timeout_s)
        finally:
            run_shell(repo_root, ["make", "docker-testenv-down"], env=examples_env, timeout_s=120)
    elif spec.id == "ex16www-monitor-url-down":
        result = run_shell(repo_root, argv, env=examples_env, timeout_s=spec.timeout_s)
        assert "PAGE_DOWN" in (result.stdout + result.stderr)
        return
    else:
        result = run_shell(repo_root, argv, env=examples_env, timeout_s=spec.timeout_s)
    assert result.returncode == 0, (
        f"{spec.id} failed\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


@pytest.fixture(scope="session")
def machine_caps(repo_root: Path):
    return probe_machine(repo_root)


@pytest.mark.examples
@pytest.mark.parametrize(
    "spec",
    [c for c in DEFAULT_COMMANDS if c.id not in {"ex02-scan", "ex03-ssh", "ex16www-dry-run"}],
    ids=lambda s: s.id,
)
def test_default_example_commands(spec: CommandSpec, repo_root: Path, examples_env, machine_caps):
    """Mock/dry-run/validate commands that must pass without special hardware."""
    missing = _missing(machine_caps, spec.requires)
    if missing:
        pytest.skip(f"missing: {', '.join(missing)}")
    _run_spec(spec, repo_root, examples_env)


@pytest.mark.examples
@pytest.mark.real
@pytest.mark.parametrize("spec", REAL_COMMANDS, ids=lambda s: s.id)
def test_real_example_commands(spec: CommandSpec, repo_root: Path, examples_env, machine_caps):
    """Real-mode variants — run when host requirements are met, else skip."""
    missing = _missing(machine_caps, spec.requires)
    if missing:
        pytest.skip(f"real mode unavailable — missing: {', '.join(missing)}")
    _run_spec(spec, repo_root, examples_env)


@pytest.mark.examples
def test_capabilities_report_written(repo_root: Path, machine_caps):
    """Session smoke: capability probe returns structured data."""
    data = machine_caps.to_dict()
    assert "probes" in data
    assert isinstance(data["available"], list)


@pytest.mark.examples
def test_command_catalog_covers_all_examples():
    """Every documented example has at least one command in the comprehensive matrix."""
    documented = {spec.id for spec in ALL_EXAMPLES}
    covered = {spec.example_id for spec in DEFAULT_COMMANDS + REAL_COMMANDS}
    assert documented - covered == set()


@pytest.mark.examples
def test_compact_flow_real_command_is_self_contained():
    """Example 15cf must not depend on a graph generated by a previous command."""
    spec = next(command for command in REAL_COMMANDS if command.id == "ex15cf-run")
    assert spec.argv[:2] == ("uri3", "run-flow")
    assert "output/weather.uri.graph.yaml" not in spec.argv[:3]
